const fs=require('fs');
const vm=require('vm');
const assert=require('assert/strict');
let state={enabled:true},listener,alarm,resolveFetch,fail=false;
const chrome={runtime:{id:'test-extension',getURL:p=>'chrome-extension://test-extension/'+p,onInstalled:{addListener(){}},onMessage:{addListener:fn=>listener=fn}},storage:{local:{
  get:async()=>structuredClone(state),set:async value=>{state={...state,...structuredClone(value)}}
}},alarms:{create(){},onAlarm:{addListener:fn=>alarm=fn}}};
vm.runInNewContext(fs.readFileSync(__dirname+'/../background.js','utf8'),{chrome,structuredClone,AbortSignal,TextEncoder,Date,fetch:()=>fail?Promise.reject(Error('offline')):new Promise(resolve=>{resolveFetch=resolve})});
const message=payload=>new Promise(resolve=>listener(payload,{id:'test-extension',url:'chrome-extension://test-extension/library.html'},resolve));
const post=id=>({type:'posts',payload:{posts:[{id,text:'synthetic'}],tier:'fetched'}});
(async()=>{
  const rejected = listener({type:'delete'}, {id:'test-extension',url:'https://x.com/home',tab:{}}, ()=>assert.fail('website must not receive control response'));
  assert.equal(rejected,undefined);
  await message(post('one'));
  const flushing=alarm({name:'flush'});
  await new Promise(r=>setImmediate(r));
  assert.equal(state.queue.posts.length,1,'persisted batch survives while request is pending');
  const arriving=message(post('two'));
  resolveFetch({ok:true,json:async()=>({ok:true,posts:1})});
  await flushing;await arriving;
  assert.deepEqual(state.queue.posts.map(p=>p.id),['two'],'new capture survives the completed flush');
  fail=true;await alarm({name:'flush'});
  assert.deepEqual(state.queue.posts.map(p=>p.id),['two'],'failed flush retains data');
  assert.equal(state.stats.lastError,'offline');
  await message({type:'set-enabled',enabled:false});
  await message(post('paused'));
  assert.equal(state.queue.posts.length,1,'pause preserves old queue but rejects new captures');
  const deletion = await message({type:'delete'});
  assert.ok(deletion.error);
  assert.equal(state.deletePending,true,'failed deletion persists across worker restarts');
  assert.equal(state.enabled,false);
  assert.equal(state.queue.posts.length,0,'delete discards queue before network request');
  const resume = await message({type:'set-enabled',enabled:true});
  assert.ok(resume.error,'cannot resume while deletion remains unfinished');
  fail=false;
  const retry=message({type:'delete'});
  await new Promise(r=>setImmediate(r));
  resolveFetch({ok:true,json:async()=>({ok:true})});
  await retry;
  assert.equal(state.deletePending,false);
  assert.equal(state.enabled,false,'successful deletion keeps capture paused');
  await message({type:'set-enabled',enabled:true});
  fail=true;
  await message({type:'posts',payload:{posts:Array.from({length:5001},(_,i)=>({id:String(i),text:'synthetic'}))}});
  assert.equal(state.queue.posts.length,5000);
  assert.equal(state.stats.dropped,1,'queue overflow is disclosed');
  state.queue={posts:[{id:'oversized',text:'x'.repeat(7*1024*1024)}],signals:[]};
  await message(post('small'));
  assert.deepEqual(state.queue.posts.map(p=>p.id),['small'],'byte overflow keeps newer captures within Chrome quota');
  fail=false;
  const badAck=alarm({name:'flush'});
  await new Promise(r=>setImmediate(r));
  resolveFetch({ok:true,json:async()=>({unexpected:true})});
  await badAck;
  assert.equal(state.queue.posts.length,1,'wrong service acknowledgment cannot erase captures');
  console.log('queue.test.js: all assertions passed');
})().catch(error=>{console.error(error);process.exitCode=1});
